version: '3.8'

services:
  inquisitor:
    container_name: inquisitor
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./inquisitor:/inquisitor
    networks:
      - local-network
    restart: unless-stopped 
  ftp-server:
    container_name: server
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    env_file:
      - dev.env
    ports:
      - "21:21"
      - "10000-10009"
    networks:
      - local-network
    restart: unless-stopped 
  ftp-client:
    build:
      context: ./ftp-client
      dockerfile: Dockerfile
    container_name: client
    networks:
      - local-network
    restart: unless-stopped

networks:
  local-network:
    driver: bridge